<?php
// Beefus CMS Configuration
// Generated by installer on 2025-07-15 03:28:44

return array(
    'database' => array(
        'host' => 'localhost',
        'port' => 3306,
        'name' => 'uncutflicks_db',
        'user' => 'uncutflicks_db',
        'password' => 'huguRwxO2WkF0ZQK',
        'charset' => 'utf8mb4'
    ),
    'redis' => array(
        'enabled' => true,
        'driver' => 'phpredis',
        'host' => '127.0.0.1',
        'port' => 6379,
        'password' => null,
        'database' => 15,
        'prefix' => 'beefus:'
    ),
    'app' => array(
        'name' => 'Beefus CMS',
        'version' => '1.0.0',
        'url' => 'https://uncutflicks.com',
        'sites_path' => '/home/httpd/html'
    ),
    'thumbnails' => array(
        'mode' => 'hotlink',
        'storage_path' => __DIR__ . '/storage/thumbnails',
        'url_path' => '/storage/thumbnails'
    )
);
